server:
  port: 8080
spring:
  dubbo:
    protocol:
      port: 2080
      name: dubbo
    registry:
      address: zookeeper://localhost:2181
    application:
      name: dubbo-provider
    scan: com.dubbo.provider.service