server:
  port: 8086
spring:
  dubbo:
    protocol:
      port: 2080
      name: dubbo
    registry:
      address: zookeeper://localhost:2181
    application:
      name: dubbo-consumer
    scan: com.dubbo.consumer.service